
name: Build (Linux)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    name: "Linux Build"
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@main

      - name: "Install dependencies"
        run: |
          sudo apt update
          sudo apt install -y build-essential clang

      - name: 'Build'
        run: |
          bash build-scripts/build-linux.sh clang
      
      - uses: actions/upload-artifact@v4
        with:
          name: linux-clang
          path: build/linux-clang/love